{"name": "test_contact_us_order_reference_validation_for_empty_message", "status": "failed", "statusDetails": {"message": "AssertionError: Error Message was not displayed.", "trace": "self = <pageobjects.contactusform.ContactUsForm object at 0x000001BAC517B438>\nerror = 'The order reference cannot be blank.'\n\n    @allure.step(\"Validate a Contact Us Form error message\")\n    def validate_error_message(self, error):\n    \ttry:\n    \t\terror_message = WebDriverWait(self.driver.instance, 10).until(\n    \t\t\tEC.visibility_of_element_located((\n>   \t\t\t\tBy.XPATH, \"//li[contains(text(), '{0}')]\".format(error))))\n\npageobjects\\contactusform.py:84: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"7863eca92a9b5ab72bd5a75c156f8e7c\")>\nmethod = <selenium.webdriver.support.expected_conditions.visibility_of_element_located object at 0x000001BAC5199940>\nmessage = ''\n\n    def until(self, method, message=''):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value is not False.\"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.time() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, 'screen', None)\n                stacktrace = getattr(exc, 'stacktrace', None)\n            time.sleep(self._poll)\n            if time.time() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:80: TimeoutException\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_contactform.ContactUsFormTestSuite testMethod=test_contact_us_order_reference_validation_for_empty_message>\n\n    def test_contact_us_order_reference_validation_for_empty_message(self):\n    \tself.homescreen = HomeScreen(self.driver)\n    \tself.homescreen.click_contact_us_button()\n    \n    \tself.contact_us_form = ContactUsForm(self.driver)\n    \tself.contact_us_form.select_subject_heading(strings.subject)\n    \tself.contact_us_form.write_email_address(strings.valid_email)\n    \tself.contact_us_form.write_message(strings.valid_message)\n    \tself.contact_us_form.click_send_button()\n>   \tself.contact_us_form.validate_error_message(strings.missing_order_reference)\n\ntestcases\\test_contactform.py:77: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pageobjects.contactusform.ContactUsForm object at 0x000001BAC517B438>\nerror = 'The order reference cannot be blank.'\n\n    @allure.step(\"Validate a Contact Us Form error message\")\n    def validate_error_message(self, error):\n    \ttry:\n    \t\terror_message = WebDriverWait(self.driver.instance, 10).until(\n    \t\t\tEC.visibility_of_element_located((\n    \t\t\t\tBy.XPATH, \"//li[contains(text(), '{0}')]\".format(error))))\n    \texcept TimeoutException:\n>   \t\tassert False, \"Error Message was not displayed.\"\nE     AssertionError: Error Message was not displayed.\n\npageobjects\\contactusform.py:86: AssertionError"}, "steps": [{"name": "Click Contact Us Button", "status": "passed", "start": 1646598404770, "stop": 1646598405841}, {"name": "Select a Subject Heading", "status": "passed", "parameters": [{"name": "subject", "value": "'Webmaster'"}], "start": 1646598405973, "stop": 1646598406004}, {"name": "Input an Email Address", "status": "passed", "parameters": [{"name": "email", "value": "'test@test.com'"}], "start": 1646598406005, "stop": 1646598406049}, {"name": "Input a Message", "status": "passed", "parameters": [{"name": "message", "value": "'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec molestie rutrum ligula ut viverra. Mauris fringilla ex nec ultrices gravida. Nam vestibulum tempus arcu eu iaculis. Vestibulum suscipit pretium ligula, eu eleifend tortor maximus non. Duis id cursus sem. Morbi sit amet pharetra ante, sit amet vulputate velit. Integer aliquam ex ipsum, vel volutpat velit dignissim sit amet. Proin malesuada ut augue in sollicitudin. Aenean aliquet metus eget commodo fringilla. Cras in pulvinar laoreet.'"}], "start": 1646598406049, "stop": 1646598406860}, {"name": "Click Send button", "status": "passed", "start": 1646598406860, "stop": 1646598408194}, {"name": "Validate a Contact Us Form error message", "status": "failed", "statusDetails": {"message": "AssertionError: Error Message was not displayed.\n", "trace": "  File \"C:\\Users\\OneMaco\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\OneMaco\\Desktop\\Jobsity\\Jobsity-QAChallenge\\AutomationPracticeFramework\\pageobjects\\contactusform.py\", line 86, in validate_error_message\n    assert False, \"Error Message was not displayed.\"\n"}, "parameters": [{"name": "error", "value": "'The order reference cannot be blank.'"}], "start": 1646598408195, "stop": 1646598418432}], "start": 1646598397099, "stop": 1646598420543, "uuid": "bef8103d-c7cd-43be-999c-4fc6703cce2b", "historyId": "d0711ce4593eca21007a1d2ca32be3b1", "testCaseId": "69b65a0e2c42a90ce8dcfe3cc32676f4", "fullName": "testcases.test_contactform.ContactUsFormTestSuite#test_contact_us_order_reference_validation_for_empty_message", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_contactform"}, {"name": "subSuite", "value": "ContactUsFormTestSuite"}, {"name": "host", "value": "DESKTOP-SSGALID"}, {"name": "thread", "value": "17704-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_contactform"}]}